import CoreGraphics
import Foundation

/// A normalized point in a glyph's coordinate space.
public struct HandDrawnPoint: Codable, Hashable, Sendable {
  public var x: Double
  public var y: Double

  public init(x: Double, y: Double) {
    self.x = x
    self.y = y
  }

  func point(in canvasSize: CGSize) -> CGPoint {
    CGPoint(
      x: x * canvasSize.width,
      y: y * canvasSize.height
    )
  }
}

/// One uninterrupted pen stroke in a glyph.
public struct HandDrawnStroke: Codable, Hashable, Identifiable, Sendable {
  public var id: UUID
  public var points: [HandDrawnPoint]

  public init(id: UUID = UUID(), points: [HandDrawnPoint]) {
    self.id = id
    self.points = points
  }
}

/// Normalized layout measurements for a glyph.
public struct HandDrawnGlyphMetrics: Codable, Hashable, Sendable {
  public var boundsX: Double
  public var boundsY: Double
  public var boundsWidth: Double
  public var boundsHeight: Double
  public var baselineY: Double
  public var xHeightY: Double

  public init(
    boundsX: Double,
    boundsY: Double,
    boundsWidth: Double,
    boundsHeight: Double,
    baselineY: Double,
    xHeightY: Double
  ) {
    self.boundsX = boundsX
    self.boundsY = boundsY
    self.boundsWidth = boundsWidth
    self.boundsHeight = boundsHeight
    self.baselineY = baselineY
    self.xHeightY = xHeightY
  }

  public func bounds(in canvasSize: CGSize) -> CGRect {
    CGRect(
      x: boundsX * canvasSize.width,
      y: boundsY * canvasSize.height,
      width: boundsWidth * canvasSize.width,
      height: boundsHeight * canvasSize.height
    )
  }

  public func baseline(in canvasSize: CGSize) -> CGFloat {
    baselineY * canvasSize.height
  }

  public func xHeight(in canvasSize: CGSize) -> CGFloat {
    xHeightY * canvasSize.height
  }
}

/// A single glyph variation and its normalized handwritten strokes.
public struct HandDrawnGlyph: Codable, Hashable, Identifiable, Sendable {
  public var id: UUID
  public var key: String
  public var variationIndex: Int
  public var canvasWidth: Double
  public var canvasHeight: Double
  public var metrics: HandDrawnGlyphMetrics
  public var strokes: [HandDrawnStroke]

  public init(
    id: UUID = UUID(),
    key: String,
    variationIndex: Int = 0,
    canvasWidth: Double,
    canvasHeight: Double,
    metrics: HandDrawnGlyphMetrics,
    strokes: [HandDrawnStroke]
  ) {
    self.id = id
    self.key = key
    self.variationIndex = variationIndex
    self.canvasWidth = canvasWidth
    self.canvasHeight = canvasHeight
    self.metrics = metrics
    self.strokes = strokes
  }

  public var canvasSize: CGSize {
    CGSize(width: canvasWidth, height: canvasHeight)
  }

  public var bounds: CGRect {
    metrics.bounds(in: canvasSize)
  }

  public var baseline: CGFloat {
    metrics.baseline(in: canvasSize)
  }

  public var xHeight: CGFloat {
    metrics.xHeight(in: canvasSize)
  }

  public var pointCount: Int {
    strokes.reduce(0) { $0 + $1.points.count }
  }

  /// Creates a glyph from normalized authoring strokes and derives its bounds.
  ///
  /// A new ID is generated by default because IDs identify immutable artwork
  /// in the render cache.
  public static func authored(
    id: UUID = UUID(),
    key: String,
    variationIndex: Int = 0,
    strokes: [HandDrawnStroke],
    canvasWidth: Double = 400,
    canvasHeight: Double = 400 / (3.0 / 4.0),
    baselineY: Double = 0.75,
    xHeightY: Double = 0.25,
    boundsPadding: Double = 0.02
  ) -> HandDrawnGlyph {
    let points = strokes.flatMap(\.points)
    let minimumX = points.map(\.x).min() ?? 0
    let maximumX = points.map(\.x).max() ?? 0
    let minimumY = points.map(\.y).min() ?? 0
    let maximumY = points.map(\.y).max() ?? 0
    let padding = max(0, boundsPadding)
    let boundsX = max(0, minimumX - padding)
    let boundsY = max(0, minimumY - padding)
    let maximumBoundsX = min(1, maximumX + padding)
    let maximumBoundsY = min(1, maximumY + padding)

    return HandDrawnGlyph(
      id: id,
      key: key,
      variationIndex: variationIndex,
      canvasWidth: canvasWidth,
      canvasHeight: canvasHeight,
      metrics: HandDrawnGlyphMetrics(
        boundsX: boundsX,
        boundsY: boundsY,
        boundsWidth: max(0, maximumBoundsX - boundsX),
        boundsHeight: max(0, maximumBoundsY - boundsY),
        baselineY: min(1, max(0, baselineY)),
        xHeightY: min(1, max(0, xHeightY))
      ),
      strokes: strokes
    )
  }
}
